### PR TITLE
Fallback to uid sorting

### LINKED ISSUE #403: Multiple contacts with the same name cause wrong highlighting/marking
## Expected behavior
If multiple contacts with the same name exists in an address book, it should be possible to select one and get this entry highlighted/marked correctly.

## Current behavior
If multiple contacts with the same name exists in an address bookm the last entry is always highlighted/marked although the first or second entry has been selected. Additionally the displayed record changes every time you click on the first entry and the last entry is still highlighted/marked.

20171025_nc-same-contact-name

### Steps to reproduce
1. Open the contacts app and create e.g. three contacts with the same name but different phone numbers.
2. Select the first entry, result: the last one is marked as active.
3. Klick on the first entry multiple times, result: the displayed record changes.

### Example VCARDs
```
BEGIN:VCARD
VERSION:3.0
FN:Anton Test
UID:afd2b8dd-4a23-40a7-8a9a-3663e6c86348
CATEGORIES:Privat
REV:20171025T173242Z
TEL;TYPE=HOME,VOICE:+49 172 11223344
END:VCARD

BEGIN:VCARD
VERSION:3.0
FN:Anton Test
UID:8a196f1a-427f-432b-b68a-079401e028c9
CATEGORIES:Privat
REV:20171025T173246Z
TEL;TYPE=HOME,VOICE:+49 172 22334455
END:VCARD

BEGIN:VCARD
VERSION:3.0
FN:Anton Test
UID:5af7c730-1481-4473-befa-bc223bc05759
CATEGORIES:Privat
REV:20171025T173250Z
TEL;TYPE=HOME,VOICE:+49 172 33445566
END:VCARD
```
#### Server Configuration
OS: Linux 3.16.47
Web server: Apache2 2.4.29
Database: MariaDB 10.0.32
PHP version: 5.6.29
Nextcloud version: 12.0.3
Contacts app version: 2.0.1

#### Client Configuration
Browser: Mozilla Firefox 56.0
Operating system: Windows 7

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #403 

@j-ed @nextcloud/contacts please review :)

~~We should rebuild the sortBy function to process the array logically instead of having some ifs here and there! :)~~

### CODE REVIEW

**Comment by skjnldsv** [comment]
> We should rebuild the sortBy function to process the array logically instead of having some ifs here and there! :)

Okay, I rebuild the function entirely, No bad coding allowed here! 💯 
The sort function now iterates between all options as fallback, if no sorting is resolved, use the second option (see debug tests as example)

```
✔ should return the first character
    LOG: 'name', 'Mb', 'Mab'
    LOG: 'name', 'Mb', 'Máa'
    LOG: 'name', 'Mab', 'Máa'
    LOG: 'name', 'Mb', 1
    LOG: 'name', 'Mab', 1
    LOG: 'name', 'Máa', 1
    LOG: 'name', 'Mb', undefined
    LOG: 'name', undefined, undefined
✔ should return the array properly sorted
    LOG: 'name', 'Test', 'Test'
    LOG: 'uid', '4321', '1234'
    LOG: 'name', 'Test', 'Test2'
    LOG: 'name', 'Test2', 1
    LOG: 'name', 'Test', 1
    LOG: 'name', 'Test', 1
```

File: js/filters/localeOrderBy_filter.js [hunk 1]
```diff
@@ -29,6 +39,10 @@ angular.module('contactsApp')
 
 			if (angular.isArray(valueA)) {
 				if (valueA[0] === valueB[0]) {
```
Comment (skjnldsv) [inline js/filters/localeOrderBy_filter.js]: We should probably also loop the array instead of supposing there is 2 elements in each one :)

File: js/filters/localeOrderBy_filter.js [hunk 2]
```diff
@@ -10,30 +10,44 @@ angular.module('contactsApp')
...
+
+				if (angular.isNumber(valueA) || typeof valueA === 'boolean') {
+					if(valueA !== valueB) {
+						return !reverseOrder ? valueA - valueB : valueB - valueA;
+					}
 				}
-				return !reverseOrder ? valueA[0].localeCompare(valueB[0]) : valueB[0].localeCompare(valueA[0]);
-			}
 
+				if (angular.isArray(valueA)) {
```
Comment (skjnldsv) [inline js/filters/localeOrderBy_filter.js]: We should probably also loop the array instead of supposing there is 2 elements in each one :)

File: js/tests/filters/localeOrderBy_filter.js [hunk 3]
```diff
@@ -10,8 +10,17 @@ describe('localeOrderBy filter', function() {
...
 		var expected = [{name: 1}, {name:'Máa'}, {name:'Mab'}, {name:'Mb'}, {name: undefined}, {name: undefined}];
 		expect(sorted).to.deep.equal(expected);
 	});
+
+	it('should return the array properly sorted by uid if the name are all equals', function() {
+		var localeOrderBy = $filter('localeOrderBy');
+		var sorted = $filter('localeOrderBy')([{name:'Test', uid: '4321'}, {name:'Test', uid: '1234'}, {name:'Test2', uid: '0000'}, {name: 1, uid: '5241'}], ['name', 'uid'], false);
+		var expected = [{name: 1, uid: '5241'}, {name:'Test', uid: '1234'}, {name:'Test', uid: '4321'}, {name:'Test2', uid: '0000'}];
+		console.log(sorted);
+		console.log(expected);
```
Comment (Henni) [inline js/tests/filters/localeOrderBy_filter.js]: These console.logs should be removed, I guess.

Comment (skjnldsv) [reply js/tests/filters/localeOrderBy_filter.js]: Ouuuups 😇

**Comment by Henni** [comment]
Seems to not change anything for me:
fix-name-sort

@skjnldsv any idea?

**Comment by skjnldsv** [comment]
@Henni are you sure the compilation is done?
Can you post your contacts vcf here please?

**Comment by irgendwie** [comment]
@skjnldsv Can reproduce @Henni's behavior when sort-by is different than 'Display name'.

**Comment by Henni** [comment]
seems like it was compiled properly...
vCards:
```
BEGIN:VCARD
VERSION:3.0
FN:a
UID:5e93e859-8570-45ec-9051-3dfebd7d182b
REV:20170914T142506Z
END:VCARD
```
```
BEGIN:VCARD
VERSION:3.0
FN:a
UID:47b4790b-e420-4ca5-9bae-8e2f003a8461
REV:20171026T114814Z
END:VCARD
```

**Comment by skjnldsv** [comment]
@irgendwie @Henni I can reproduce too! Will fix asap.

**Comment by Henni** [comment]
reverted a commit that should have gone to another branch... :see_no_evil:

**Comment by skjnldsv** [comment]
@Henni I was wondering too ^^
You could have rebased instead?

**Comment by skjnldsv** [comment]
Fixed, please update reviews! :)
@Henni @irgendwie

**Comment by skjnldsv** [comment]
Will add tests to fit your bug in a minute! ;)

File: js/filters/localeOrderBy_filter.js [hunk 4]
```diff
@@ -10,30 +10,45 @@ angular.module('contactsApp')
...
+				if (angular.isFunction(valueB)) {
+					valueB = b[sortBy]();
+				}
 
-			if (angular.isArray(valueA)) {
-				if (valueA[0] === valueB[0]) {
-					return !reverseOrder ? valueA[1].localeCompare(valueB[1]) : valueB[1].localeCompare(valueA[1]);
+				// Start sorting
+				if (angular.isString(valueA)) {
+					if(valueA !== valueB) {
```
Comment (Henni) [inline js/filters/localeOrderBy_filter.js]: you can get rid of this, as well as lines 37 and 44.

File: js/filters/localeOrderBy_filter.js [hunk 5]
```diff
@@ -10,30 +10,45 @@ angular.module('contactsApp')
...
+						return !reverseOrder ? valueA.localeCompare(valueB) : valueB.localeCompare(valueA);
```
Comment (Henni) [inline js/filters/localeOrderBy_filter.js]: I suggest removing the `!` and flipping the both expressions. (also lines 38, 45 and 48)

**Comment by Henni** [comment]
We are close to 100% test coverage in this file. Do you want to complete it?
https://codecov.io/gh/nextcloud/contacts/compare/6dabbc756b9e2aef4ff2ff63fff5679da96c7728...7146194a237d644f1759635654157b2b2f4ecfa4/src/js/filters/localeOrderBy_filter.js?before=js/filters/localeOrderBy_filter.js

File: js/filters/localeOrderBy_filter.js (hunk 4 above)
Comment (skjnldsv) [reply js/filters/localeOrderBy_filter.js]: No I can't, otherwise it won't fallback to the second sorting option.

**Comment by skjnldsv** [comment]
> We are close to 100% test coverage in this file. Do you want to complete it?

What's left to do for 100%?

**Comment by Henni** [comment]
@skjnldsv take a look at [codecov](https://codecov.io/gh/nextcloud/contacts/compare/6dabbc756b9e2aef4ff2ff63fff5679da96c7728...7146194a237d644f1759635654157b2b2f4ecfa4/src/js/filters/localeOrderBy_filter.js?before=js/filters/localeOrderBy_filter.js). Some branches aren't covered yet.

**Comment by skjnldsv** [comment]
I'm changing stuff, will update this afternoon!! :)
