### PR TITLE
Validate rev prodid version and validation edit

### LINKED ISSUE #129: Error in vcard multiple REV/PRODID fields - This card is corrupted and has been fixed
### Steps to reproduce
1. Login, choose contacts app
2. Since latest version, I see an exclamation point next to many contacts, stating to check automatically fixed data and request to force a save. I do this by removing or adding some data. Exclamation point disappears.
3. Switch to other Nextcloud application and back to Contacts. Exclamation point is back and changes are not saved.

### Expected behaviour
I would expect the indicated fixed issue with the vcard to be permanently fixed and changed information to be saved.

### Actual behaviour
I keep seeing the exclamation points and changed data is not saved.

### Server configuration
**Operating system**: 
Debian Testing 9.0

**Web server:**
Apache/2.4.25 (Debian)

**Database:**
postgresql-9.6  9.6.1-2 amd64

**PHP version:**
php7.0  7.0.15-1
php -v
PHP 7.0.15-1 (cli) (built: Jan 25 2017 10:17:41) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.15-1, Copyright (c) 1999-2017, by Zend Technologies

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 11.0.1 (stable)
**Contacts version:** (see Nextcloud apps page)
1.5.3
**Updated from an older Nextcloud or fresh install:**
Nextcloud updated several times, but problem started after latest Contact app update.
**Signing status:**
No errors have been found.

**List of activated apps:**
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - bookmarks: 0.9.1
  - calendar: 1.5.0
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.2
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - ojsxc: 3.0.2
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - ocsms
  - templateeditor
  - user_external
  - user_ldap
  - user_saml

**The content of config/config.php:**
```
{
    "system": {
        "instanceid": "ochf368ebq3c",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.example.com"
        ],
        "datadirectory": "\/var\/nc_data",
        "overwrite.cli.url": "https:\/\/nextcloud.example.com",
        "dbtype": "pgsql",
        "version": "11.0.1.2",
        "dbname": "nextcloud",
        "dbhost": "dbserver.example.com",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "mail_smtpmode": "smtp",
        "mail_from_address": "webmaster",
        "mail_domain": "example.com",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtphost": "smtp.example.com",
        "mail_smtpport": "25",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "singleuser": false,
        "loglevel": 2,
        "debug": false,
        "appstore.experimental.enabled": true,
        "theme": ""
    }
}
```
**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox, Chromium

**Operating system:**
Opensuse Tumbleweed
**CardDAV-clients:**
Not relevant probably as I experience this problem from the browser interface.
Akonadi connector, CardDAV-Sync on Android 0.4.20, Outlook CalDav Synchronizer
#### Web server error log
/var/log/apache2/error_nextcloud.log is empty

#### Nextcloud log (data/nextcloud.log)
Below is just one entry, there are many.
```
{"reqId":"i9AxBA1cpY\/b06\/NPHYu","remoteAddr":"2a02:1807:2600:100::101","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 415 Validation error in vCard: PRODID MUST NOT appear more than once in a VCARD component\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\UnsupportedMediaType\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CardDAV\\\/Plugin.php(294): Sabre\\\\CardDAV\\\\Plugin->validateVCard('BEGIN:VCARD\\\\r\\\\nVE...', false)\\n#1 [internal function]: Sabre\\\\CardDAV\\\\Plugin->beforeWriteContent('addressbooks\\\/us...', Object(Sabre\\\\CardDAV\\\\Card), 'BEGIN:VCARD\\\\r\\\\nVE...', false)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1104): Sabre\\\\Event\\\\EventEmitter->emit('beforeWriteCont...', Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->updateFile('addressbooks\\\/us...', 'BEGIN:VCARD\\\\r\\\\nVE...', NULL)\\n#5 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Server.php(227): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(30): OCA\\\\DAV\\\\Server->exec()\\n#11 \\\/var\\\/www\\\/nextcloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/nextcl...')\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CardDAV\\\/Plugin.php\",\"Line\":397,\"User\":\"peter\"}","level":4,"time":"2017-02-10T15:08:29+00:00","method":"PUT","url":"\/remote.php\/dav\/addressbooks\/users\/peter\/contacts\/185f70a9-5ca0-4e38-a1bf-43ec601e059b.vcf","user":"peter","version":"11.0.1.2"}
```
#### Browser log
From Chromium console
```
dav.js?v=52e17de…:3641 PUT https://nextcloud.example.com/remote.php/dav/addressbooks/users/peter/contacts/185f70a9-5ca0-4e38-a1bf-43ec601e059b.vcf 415 (Unsupported Media Type)
send @ dav.js?v=52e17de…:3641
callee$2$0$ @ dav.js?v=52e17de…:3156
tryCatch @ dav.js?v=52e17de…:121
invoke @ dav.js?v=52e17de…:294
Gp.(anonymous function) @ dav.js?v=52e17de…:330
onFulfilled @ dav.js?v=52e17de…:3737
(anonymous) @ dav.js?v=52e17de…:3726
co @ dav.js?v=52e17de…:3722
send @ dav.js?v=52e17de…:3134
updateObject @ dav.js?v=52e17de…:3415
updateCard @ dav.js?v=52e17de…:1799
updateCard @ dav.js?v=52e17de…:1524
update @ contact_service.js:171
ctrl.updateContact @ contactDetails_controller.js:72
fn @ VM597:4
$eval @ angular.js?v=52e17de…:17682
(anonymous) @ angular.js?v=52e17de…:24916
(anonymous) @ angular.js?v=52e17de…:27691
forEach @ angular.js?v=52e17de…:321
$$writeModelToScope @ angular.js?v=52e17de…:27689
writeToModelIfNeeded @ angular.js?v=52e17de…:27682
(anonymous) @ angular.js?v=52e17de…:27676
validationDone @ angular.js?v=52e17de…:27603
processAsyncValidators @ angular.js?v=52e17de…:27586
$$runValidators @ angular.js?v=52e17de…:27530
$$parseAndValidate @ angular.js?v=52e17de…:27669
$commitViewValue @ angular.js?v=52e17de…:27637
(anonymous) @ angular.js?v=52e17de…:27774
(anonymous) @ angular.js?v=52e17de…:19612
completeOutstandingRequest @ angular.js?v=52e17de…:5964
(anonymous) @ angular.js?v=52e17de…:6243
dav.js?v=52e17de…:3649 Uncaught (in promise) Error: Bad status: 415
    at XMLHttpRequest.request.onreadystatechange (dav.js?v=52e17de…:3649)

```

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #129 
- Keep only one rev/version/prodid field in case of multiple ones
    - [x] Autosave
    - [x] Keep first item only
- [x] Added some animation for the save button

### CODE REVIEW

**Comment by skjnldsv** [comment]
Bump, we're close to the 2.0 release! ❤️

**Comment by skjnldsv** [comment]
Weekly bump @Henni @irgendwie @jancborchardt ❤️

File: js/models/contact_model.js [hunk 1]
```diff
@@ -197,7 +197,7 @@ angular.module('contactsApp')
 					}
 				} else {
 					// getter
-					var property = this.validate('categories', this.getProperty('categories'));
+					var property = this.getProperty('categories');
```
Comment (Henni) [inline js/models/contact_model.js]: These are unrelated changes, right? Or do they have anything to do with issue #129 ?

File: js/models/contact_model.js [hunk 2]
```diff
@@ -361,6 +361,18 @@ angular.module('contactsApp')
 			/* eslint-disable no-console */
 			validate: function(prop, property) {
 				switch(prop) {
+				case 'rev':
+				case 'prodid':
+				case 'version':
+					if (!angular.isUndefined(this.props[prop])) {
+						if(this.props[prop].length > 1) {
```
Comment (Henni) [inline js/models/contact_model.js]: You can put both conditions in a single if statement. That would reduce the code nesting.

File: js/services/contact_service.js [hunk 3]
```diff
@@ -46,6 +45,16 @@ angular.module('contactsApp')
 							});
 						}).then(function (contacts_) {
 							contacts_.map(function (contact) {
+								// Validate some fields
+								contact.validate('rev');
+								contact.validate('prodid');
+								contact.validate('version');
```
Comment (Henni) [inline js/services/contact_service.js]: I would suggest to move these three validations to a `contact.fix()` method, which returns whether anything has changed an the contact has to be updated. This way we know where to find it, when we want to add other stuff that should be automatically fixed.
What do you think?

File: js/models/contact_model.js (hunk 1 above)
Comment (skjnldsv) [reply js/models/contact_model.js]: The validate is now integrated into the getProperty function :)

File: js/services/contact_service.js (hunk 3 above)
Comment (skjnldsv) [reply js/services/contact_service.js]: I'm OK with this :)

**Comment by skjnldsv** [comment]
There is a bug too. I can't get the autoupdate to work anymore, don't know why.
I think it's because of the lazy loading, since the requested fields don't include rev, prodid nor version! :)

**Comment by skjnldsv** [comment]
@irgendwie any news?

File: js/services/contact_service.js [hunk 4]
```diff
@@ -46,6 +45,11 @@ angular.module('contactsApp')
 							});
 						}).then(function (contacts_) {
 							contacts_.map(function (contact) {
+								// Validate some fields
+								if(contact.fix()) {
+									// Can't use this in those nested functions
+									contactService.update(contact);
+								}
 								contacts.put(contact.uid(), contact);
```
Comment (Henni) [inline js/services/contact_service.js]: This `contacts` references the parameter in line 26.
We should rename the cache to something like `contactsCache` to prevent these name collisions.

**Comment by skjnldsv** [comment]
@irgendwie @Henni @jancborchardt please take a look!
This is done (finally)! :D

**Comment by skjnldsv** [comment]
Rebased with latest scss changes.

File: templates/contactList.html [hunk 5]
```diff
@@ -1,6 +1,6 @@
 <div style="height: 90%" class="contacts-list" ng-class="{loading: ctrl.loading, 'mobile-show': ctrl.show}">
         <div class="app-content-list-item"
-			 ng-repeat="contact in ctrl.contactList = (ctrl.contacts | contactGroupFilter:ctrl.routeParams.gid | localeOrderBy:ctrl.sortBy | filter:query | limitTo:ctrl.limitTo) as filtered track by contact.uid()"
+			 ng-repeat="contact in (ctrl.contactList | contactGroupFilter:ctrl.routeParams.gid | localeOrderBy:ctrl.sortBy | filter:query | limitTo:ctrl.limitTo) as filtered track by contact.uid()"
```
Comment (Henni) [inline templates/contactList.html]: Because of this change you need to fix the `emptycontent` and use `filtered.length`:
```js
<div ng-show="!filtered.length && !ctrl.loading && ctrl.searchTerm !== ''">
```

Comment (skjnldsv) [reply templates/contactList.html]: Good catch!!

**Comment by irgendwie** [comment]
I'm a bit unhappy, that we need to decide which REV, PROPID and VERSION we want to keep. But we won't be able to determine which application produced the VCARD in the first place. Same goes for the other properties. 😪

**Comment by skjnldsv** [comment]
@irgendwie well, we could work on this a bit.
Right now, we only keep the first one, but in the future, we could: 
 - Reset the REV to the current date since we're backing it up
 - Replace the PRODID by a string of ours (Nextcloud 1.5.3 for ex)
 - Keep the lowest VERSION ?

**Comment by irgendwie** [comment]
- It doesn't matter what we do with the REV property, since it gets updatet when syncing the repaired vcard.
- PRODID describes the client which created the vcard -> I'm not sure if I really want to say, that we created the vcard if we didn't do it but we could do this, yeah - still it's not a required field
- For the version we should specify the version the vcard is written in => therefore 3.0 since we produce vcards in version 3.0?

**Comment by skjnldsv** [comment]
Okay, but what if it has ?
```
VERSION 3.0
VERSION 4.0
```

**Comment by irgendwie** [comment]
@skjnldsv Let's look into our version compatibility for the next release, we should finally define, which version of vcard we are using and enforce all properties accordingly.

**Comment by skjnldsv** [comment]
Agreed!
