### PR TITLE
Fix export and version comparison

### LINKED ISSUE #39: Currently not possible to download group of contacts.
At the moment it is not possible to select a single group of contacts and export/download it as a vcard file.
This used to be possible with the older contact app (last year) 
Can this feature be re-added again?

Regards,

Bert

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39513291-currently-not-possible-to-download-group-of-contacts?utm_campaign=plugin&utm_content=tracker%2F46751899&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F46751899&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by skjnldsv**
We can have the export back! 🎉 

fix #39 
@irgendwie @brjhaverkamp

### CODE REVIEW

File: js/components/addressBook/addressBook_controller.js [hunk 1]
```diff
@@ -4,8 +4,22 @@ angular.module('contactsApp')
 
 	ctrl.showUrl = false;
 	/* globals oc_config */
+
+	function compareVersion(version1, version2) {
+		var result=false;
+		for(var i=0;i<(Math.max(version1.length, version2.length));i++) {
```
Comment (ChristophWurst) [inline js/components/addressBook/addressBook_controller.js]: shouldn't it be Math.min? You don't want to access an index greater than the string length, do you? :-)

File: js/components/addressBook/addressBook_controller.js [hunk 2]
```diff
@@ -4,8 +4,22 @@ angular.module('contactsApp')
...
+			if(Number(version1[i])<Number(version2[i])) {
+				result=true;
```
Comment (ChristophWurst) [inline js/components/addressBook/addressBook_controller.js]: simple ``return true;``?

File: js/components/addressBook/addressBook_controller.js [hunk 3]
```diff
@@ -4,8 +4,22 @@ angular.module('contactsApp')
...
+				break;
+			}
+			if(version1[i]!==version2[i]) {
```
Comment (ChristophWurst) [inline js/components/addressBook/addressBook_controller.js]:
```js
if(version1[i] !== version2[i]) {
   return false; // version 2 is higher
}
```

Otherwise: do nothing and continue with the next digit.

Comment (skjnldsv) [inline js/components/addressBook/addressBook_controller.js]: Yeah, I snapped this code from somewhere and didn't even realised how poorly it was written...
Please forgive me! 😢

File: js/components/addressBook/addressBook_controller.js (hunk 1 above)
Comment (skjnldsv) [inline js/components/addressBook/addressBook_controller.js]: Yes we do.
If we're comparing 9.0.0 and 9.0.0.1 we still need to check the last value. But I need to add a safety conversion if NaN or undefined.

**Comment by skjnldsv** [comment]
@ChristophWurst Fixed and rewritten 😊

**Comment by ChristophWurst** [comment]
nice! code looks good now

**Comment by ChristophWurst** [comment]
you could add a unit test for this function 😉

**Comment by skjnldsv** [comment]
I coulc I could... 😂

**Comment by ChristophWurst** [comment]
merge? 🙈 🙊 🙉

**Comment by skjnldsv** [comment]
Since it's a function inside a controller, I don't think I can do tests directly :)
Soooo, let's merge? 😄

**Comment by ChristophWurst** [comment]
> Since it's a function inside a controller, I don't think I can do tests directly :)

You could export but prefix it with an underscore ;-)

**Comment by skjnldsv** [comment]
But is it really necessary? :D 
Let's not over-complicate things!

**Comment by brjhaverkamp** [comment]
Thanks for fixing this. I'm still trying to figure out how this version comparison will solve the export of single address groups. But I am eager to give it a try. Will this be released alongside NC 11? Or how can I try this best?
