### PR TITLE
Fix:Form is transitioned into view mode when saving fails

### LINKED ISSUE #3375: [Contact Details] Form is transitioned into view mode when saving fails
### Describe the bug

Editing a contact and then saving transitions the form into view mode. However, this also happens when saving fails (due to a failed request).

### Steps to reproduce

1. Open a contact.
2. Block all requests to save this contact in your dev tools (e.g. `https://localhost/remote.php/dav/addressbooks/users/admin/contacts/3320F7FA-FAF9-44C6-BD00-900646E6CF5E.vcf`).
3. Click on `Edit`.
4. Make some changes.
5. Save the contact by clicking on `Save`.
6. The form switches to view mode.

### Expected behavior

There should be a toast indicating the error and the form should stay in edit mode.

### Actual behavior

The form switches to view mode and I, as a user, have no idea that saving failed. It looks to me as if saving the contact was successful.

### Contact version

main

### PR DESCRIPTION
**Pull request by hamza221**
fixes #3375

### CODE REVIEW

File: src/components/ContactDetails.vue [hunk 1]
```diff
@@ -854,8 +854,12 @@ export default {
 		 * Save the contact. This handler is triggered by the save button.
 		 */
 		async onSave() {
-			await this.updateContact()
-			this.editMode = false
+			try {
+				await this.updateContact()
+				this.editMode = false
+			} catch (error) {
+				showError(t('contacts', 'Unable to update contact'))
```
Comment (ChristophWurst) [inline src/components/ContactDetails.vue:861]: the error will go silent now. could you add an error.log in a follow-up pr? :)

Comment (hamza221) [reply src/components/ContactDetails.vue:861]: it's logged in contacts.js then thrown again
