### PR TITLE
Fix duplicate groups

### LINKED ISSUE #112: Groups doesn't support duplicate values
<strike>After #85 
If all the groups are joined by a single coma without escaping, angular generate an error</strike>

Nope, this is due to duplicate values. We can't have `test,test,test2`.

``` javascript
angular.js?v=8339131…:13920 Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: $item in $select.selected, Duplicate key: string:test, Duplicate value: test
http://errors.angularjs.org/1.5.8/ngRepeat/dupes?p0=%24item%20in%20%24select.selected&p1=string%3Atest&p2=test
    at angular.js?v=8339131…:68
    at ngRepeatAction (angular.js?v=8339131…:29821)
    at $watchCollectionAction (angular.js?v=8339131…:17383)
    at Scope.$digest (angular.js?v=8339131…:17524)
    at Scope.$apply (angular.js?v=8339131…:17790)
    at done (angular.js?v=8339131…:11831)
    at completeRequest (angular.js?v=8339131…:12033)
    at XMLHttpRequest.requestLoaded (angular.js?v=8339131…:11966)
```

vcard: 
[test.txt](https://github.com/nextcloud/contacts/files/749711/test.txt)

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #112
Test: [test.txt](https://github.com/nextcloud/contacts/files/753225/test.txt) [contacts.tar.gz](https://github.com/nextcloud/contacts/files/753229/contacts.tar.gz)

Procedure: Import vcf, groups should be `test, test2` and a debug log should be in the console. No warning.

@nextcloud/contacts

### CODE REVIEW

File: js/models/contact_model.js [hunk 1]
```diff
@@ -327,7 +327,7 @@ angular.module('contactsApp')
 					if(!angular.equals(uniqueCategories, property.value)) {
 						this.failedProps.push(prop);
 						property.value = uniqueCategories;
-						console.debug(this.uid()+': Categories duplicate: ' + property.value);
+						//console.debug(this.uid()+': Categories duplicate: ' + property.value);
```
Comment (skjnldsv) [inline js/models/contact_model.js]: Can someone help with the tests? Why is having `console.debug` breaks things?

Comment (skjnldsv) [inline js/models/contact_model.js]: @nextcloud/javascript

Comment (irgendwie) [inline js/models/contact_model.js]: Let's take a look at this for the next release.
