### PR TITLE
Workaround for bug that prevented editing vCards with commas in the address

### LINKED ISSUE #1009: Unable to edit any contacts
### Describe the bug
When editing any field of a contact (e.g. adding or deleting an email address), a loading indicator appears, but nothing happens. An error is visible in the JavaScript console:
```
Unhandled promise rejection TypeError: "t.replace is not a function"

    _rfc6868Unescape https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:7 property https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:7 component https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:7 r https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:7 t https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:112 _ https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:7 _invoke https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:7 e https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:7 vn https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:91 a https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:91 yn https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:91 O https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:7 yn https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:91 updateContact https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:112 Ge https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:41 dispatch https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:47 dispatch https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:41 t https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:177 _ https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:7 _invoke https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:7 e https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:7 ar https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:177 a https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:177 sr https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:177 O https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:7 sr https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:177 updateContact https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:177 add https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:7 _tryToStartAnother https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:7 add https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:7 O https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:7 add https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:7 debounceUpdateContact https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:177 u https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:245 

contacts.js:7:155176

    e https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:7 exports https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:7 L https://[redacted]/apps/contacts/js/contacts.js?v=73c53709-20:7 v https://[redacted]/apps/notifications/js/notifications.js?v=73c53709-20:14 v https://[redacted]/apps/notifications/js/notifications.js?v=73c53709-20:14 s https://[redacted]/apps/notifications/js/notifications.js?v=73c53709-20:14 
```

**To Reproduce**
1. Edit a contact with Firefox

**Expected behavior**
The edit is saved

**Actual behavior**
It stays loading forever and does not apply the update

### Server configuration

**Operating system**: Linux

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud version:** 15.0.5

**Contacts version:** 3.0.5

**Updated from an older Nextcloud or fresh install:** Updated from 14.x

**Signing status:**
```
No errors have been found.
```

**List of activated apps:**
```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - audioplayer: 2.6.1
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - camerarawpreviews: 0.6.5
  - checksum: 0.4.2
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.5
  - data_request: 1.2.0
  - dav: 1.8.1
  - drop_account: 0.1.0
  - encryption: 2.3.0
  - external: 3.2.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_external: 1.6.0
  - files_markdown: 2.0.5
  - files_pdfviewer: 1.4.0
  - files_rightclick: 0.11.1
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - group_everyone: 0.1.1
  - groupfolders: 2.0.4
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - metadata: 0.9.0
  - news: 13.1.4
  - nextcloud_announcements: 1.4.0
  - notes: 2.5.1
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - qownnotesapi: 18.11.0
  - quota_warning: 1.4.0
  - ransomware_protection: 1.3.0
  - richdocuments: 3.2.4
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - socialsharing_email: 1.0.5
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_admin: 0.2.0
  - twofactor_backupcodes: 1.4.1
  - twofactor_gateway: 0.12.0
  - twofactor_nextcloud_notification: 1.0.3
  - twofactor_totp: 2.1.2
  - updatenotification: 1.5.0
  - w2g2: 2.2.4
  - workflow_script: 1.0.1
  - workflowengine: 1.5.0
Disabled:
  - caniupdate
  - drawio
  - end_to_end_encryption
  - fulltextsearch
  - fulltextsearch_elasticsearch
  - music
  - polls
  - tasks
  - unsplash
  - user_external
  - user_ldap

```

**Nextcloud configuration:**
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.lynnesbian.space"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.5.3",
        "overwrite.cli.url": "https:\/\/cloud.lynnesbian.space",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "loglevel": 2,
        "updater.release.channel": "stable",
        "theme": "",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\Movie",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF"
        ]
    }
}

```

### Client configuration
**Browser:** Firefox 65.0.1

**Operating system:** Linux

**CardDAV-clients:** N/A

#### *Web server error log*
```
N/A
```

#### *data/nextcloud.log*
```
N/A
```

#### Browser log
```
(see above)
```

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/71768744-unable-to-edit-any-contacts?utm_campaign=plugin&utm_content=tracker%2F46751899&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F46751899&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #1313: broken contacts could not be fixed in the app by clicking the above right icon...
### Describe the bug
On several contacts there was a hint in the above right corner:This contact was broken and received a fix. Please review the content and click here to save it.

By doing this most of the contacts are fixed.

But 5 contacts couldn't be fixed this way. After clicking the 'arrow up' a rotating circle appears and stays there didn't stop to rotate...

**To Reproduce**
1. Logon to Nextcloud
2. Click on 'Contacts'
3. Select a contact and clickt the 'arrow up'
4. rotating circle appears for ever ...

**Expected behavior**
After clicking the arrow, I see a rotating circle for a short time, then it disappears and the contact ist saved.

**Screenshots**

### Server configuration

**Operating system**: Ubuntu Server 18.04.3 LTS

**Web server:** Apache 2.4.29

**Database:** MariaDB 10.1.41

**PHP version:** 7.2.19

**Nextcloud version: 16.0.5

**Contacts version: 3.1.6

**Updated from an older Nextcloud or fresh install:Updated

**Signing status:**
Don't know what to put here...
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.

**List of activated apps:**

Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - bruteforcesettings: 1.4.0
  - calendar: 1.7.1
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.6
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_external: 1.7.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notes: 3.0.3
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - twofactor_totp: 3.0.1
  - updatenotification: 1.6.0
  - viewer: 1.1.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - encryption
  - files_trashbin
  - files_versions
  - user_ldap

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.2.111",
            "cpunke.de",
            "ubuntu"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cpunke.de\/owncloud",
        "dbtype": "mysql",
        "version": "16.0.5.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "log_rotate_size": 104857600,
        "theme": "",
        "maintenance": false,
        "filesystem_check_changes": 1,
        "trashbin_retention_obligation": "7,8",
        "versions_retention_obligation": "7,8",
        "appstore.experimental.enabled": false,
        "default_language": "de",
        "defaultapp": "",
        "updatechecker": false,
        "enable_previews": true,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mysql.utf8mb4": true,
        "app_install_overwrite": [
            "calendar"
        ]
    }
}
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

### Client configuration
**Browser: Firefox 69.0.3 (64-bit)**

**Operating system: Linux Mint 19.2 Tina**

**CardDAV-clients: Android DAVx5**

#### *Web server error log*
```
Insert your webserver log here
```

#### *data/nextcloud.log*
```
Insert your Nextcloud log here
nextcloud.log is empty

#### Browser log
<details>
<summary>How to access your browser console (Click to expand)</summary>

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.


Insert your browser log here, this could for example include:

a) Console Log:
JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:494
New search handler registered search.js:67:12
Connected to dav! 
Object { rootUrl: "https://cpunke.de/owncloud/remote.php/dav/", advertisedFeatures: (17) […], currentUserPrincipal: {…}, principalCollections: (4) […], calendarHomes: [], publicCalendarHome: {…}, addressBookHomes: (1) […], parser: {…}, _isConnected: true, _request: {…} }
Contacts.vue:299
The escapeHTML library is deprecated! It will be removed in nextcloud 19. 13 globals.js:30:10
The escapeHTML library is deprecated! It will be removed in nextcloud 19. 4 globals.js:30:10
The following contact needed a correction that failed: duplicate types 
Object { jCal: (3) […], addressbook: {…}, vCard: {…}, conflict: false, dav: {…} }
validate.js:38:14
Locale used de PropertyDateTime.vue:171
TypeError: "t.replace is not a function"
    _rfc6868Unescape ical.js:1657
    property ical.js:1493
    toICALString ical.js:3123
    fix duplicateTypes.js:47
    fix duplicateTypes.js:46
    Sn validate.js:36
    Sn validate.js:31
    updateLocalContact ContactDetails.vue:580
    e ContactDetails.vue:494
    u ncvuecomponents.js:298
    _invoke ncvuecomponents.js:298
    e ncvuecomponents.js:298
    Wn contacts.js:1129
    a contacts.js:1129
duplicateTypes.js:60:11
The following contact needed a correction that failed: duplicate types 
Object { jCal: (3) […], addressbook: {…}, vCard: {…}, conflict: false, dav: {…} }
validate.js:38:14
The following contact has been repaired: invalid REV 
Object { jCal: (3) […], addressbook: {…}, vCard: {…}, conflict: false, dav: {…} }
validate.js:42:14
Locale used de PropertyDateTime.vue:171
TypeError: "t.replace is not a function"
    _rfc6868Unescape ical.js:1657
    property ical.js:1493
    toICALString ical.js:3123
    fix duplicateTypes.js:47
    fix duplicateTypes.js:46
    Sn validate.js:36
    Sn validate.js:31
    t contacts.js:326
    u ncvuecomponents.js:298
    _invoke ncvuecomponents.js:298
    e ncvuecomponents.js:298
    ln contacts.js:1022
    a contacts.js:1022
    fn contacts.js:1022
    fn contacts.js:1022
    updateContact contacts.js:280
    h vuex.esm.js:732
    dispatch vuex.esm.js:437
    dispatch vuex.esm.js:331
    t ContactDetails.vue:433
    u ncvuecomponents.js:298
    _invoke ncvuecomponents.js:298
    e ncvuecomponents.js:298
    Wn contacts.js:1129
    a contacts.js:1129
    qn contacts.js:1129
    qn contacts.js:1129
    updateContact ContactDetails.vue:426
    VueJS 3
duplicateTypes.js:60:11
The following contact needed a correction that failed: duplicate types 
Object { jCal: Getter & Setter, addressbook: Getter & Setter, vCard: Getter & Setter, conflict: Getter & Setter, dav: Getter & Setter, … }
validate.js:38:14
TypeError: "t.replace is not a function"
    _rfc6868Unescape ical.js:1657
    property ical.js:1493
    component ical.js:1444
    r ical.js:1406
    t contacts.js:333
    u ncvuecomponents.js:298
    _invoke ncvuecomponents.js:298
    e ncvuecomponents.js:298
    ln contacts.js:1022
    a contacts.js:1022
    fn contacts.js:1022
    fn contacts.js:1022
    updateContact contacts.js:280
    h vuex.esm.js:732
    dispatch vuex.esm.js:437
    dispatch vuex.esm.js:331
    t ContactDetails.vue:433
    u ncvuecomponents.js:298
    _invoke ncvuecomponents.js:298
    e ncvuecomponents.js:298
    Wn contacts.js:1129
    a contacts.js:1129
    qn contacts.js:1129
    qn contacts.js:1129
    updateContact ContactDetails.vue:426
    VueJS 3
b) The network log:
see screenshot1.jpg + screenshot2.jpg
![screenshot1](https://user-images.githubusercontent.com/30260653/67425376-2be9e280-f5d8-11e9-9200-bb4d9a8c1165.jpg)
![screenshot2](https://user-images.githubusercontent.com/30260653/67425393-30160000-f5d8-11e9-87b6-825a8b20c957.jpg)

### PR DESCRIPTION
**Pull request by hanzi**
This is a workaround that fixes #1009 
(also fixes #1313)

Without it, contacts whose address contains a comma (quite common in Asian addresses) cannot be edited in the web interface.

I am aware that this is actually an upstream bug (mozilla-comm/ical.js#386) and should be fixed there... but that PR is about 10 months old and it is unclear when it might be merged and tagged. Meanwhile, this leads to very poor user experience in the Contacts app.

This fix would not conflict with that upstream PR since it merely makes it explicit that `LABEL` cannot contain multiple values.

### CODE REVIEW

**Comment by skjnldsv** [comment]
As mentioned in https://github.com/nextcloud/contacts/pull/1393#issuecomment-571038840
Please put those patches in another dedicated file :)

File: src/services/updateDesignSet.js [hunk 1]
```diff
@@ -0,0 +1,111 @@
+/**
+ * @copyright Copyright (c) 2019 John Molakvoæ <skjnldsv@protonmail.com>
```
Comment (skjnldsv) [inline src/services/updateDesignSet.js]: This is your code :)

Comment (hanzi) [reply src/services/updateDesignSet.js]: Part of it is still yours, just moved in from another file. But I added another line 👍

**Comment by hanzi** [comment]
@skjnldsv I have now tried to re-use the existing flow for updating the design set and extracting it into its own service.

I will update #1393 once this is merged.

File: src/mixins/PropertyMixin.js [hunk 2]
```diff
@@ -21,7 +21,7 @@
  */
 import debounce from 'debounce'
 import Contact from '../models/contact'
-import ICAL from 'ical.js'
+import setPropertyAlias from '../services/updateDesignSet'
```
Comment (skjnldsv) [inline src/mixins/PropertyMixin.js]: Hum, this would be the default export, not the function

File: src/services/updateDesignSet.js (hunk 1 above)
Comment (skjnldsv) [reply src/services/updateDesignSet.js]: The file is yours, I'm just an author :)
One copyright per file ;)

File: src/mixins/PropertyMixin.js (hunk 2 above)
Comment (hanzi) [reply src/mixins/PropertyMixin.js]: Augh. That sneaky Quality Review thingy previously flagged it as an error, so I just believed it... https://app.codacy.com/manual/skjnldsv/contacts/commit?cid=430033681&fileBranchId=15882771#newIssuesView

Comment (skjnldsv) [reply src/mixins/PropertyMixin.js]: DOn't listent too much to this tool, it's not very great to be honest :/

File: src/services/updateDesignSet.js (hunk 1 above)
Comment (hanzi) [reply src/services/updateDesignSet.js]: Updated

**Comment by caugner** [comment]
@hanzi FYI The PRs in `ical.js` have been merged, so the next `ical.js` version will include the fixes.
