### PR TITLE
Fix empty content for settings dialogs

### LINKED ISSUE #2944: Import dialogue shows no text
### Describe the bug

Bildschirmfoto vom 2022-09-20 10-15-07

### Steps to reproduce

1. Open the app settings
2. Import previously exported contacts

### Expected behavior

Meaningful text in the modal

### Actual behavior

Only a logo, no text in the modal

### Contact version

v5

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by GretaD**
fixes #2944

to do

- [x] Check other places where this problem is shown. Empty content doesnt use template anymore
- [x] Change button, to ButtonVue

after
Screenshot from 2022-10-14 13-15-14

### CODE REVIEW

File: src/components/ProcessingScreen.vue [hunk 1]
```diff
@@ -1,18 +1,13 @@
...
-		<template #desc>
-			<div class="processing-screen__progress">
-				<progress :max="total" :value="progress" />
-			</div>
-			<div class="processing-screen__desc">
-				<slot name="desc" />
-			</div>
-		</template>
-	</EmptyContent>
+	<div>
```
Comment (ChristophWurst) [inline src/components/ProcessingScreen.vue:2]: I'm just curious, but why do we need the wrapping div?

Comment (ChristophWurst) [reply src/components/ProcessingScreen.vue:2]: Nevermind. There would be two root elements otherwise.

File: src/components/ProcessingScreen.vue [hunk 2]
```diff
@@ -1,18 +1,13 @@
...
+		<EmptyContent :description="desc"
+			:title="title"
+			class="processing-screen__wrapper">
+			<template #icon>
+				<IconContact :size="20" />
+			</template>
+		</EmptyContent><progress :max="total" :value="progress" />
```
Comment (ChristophWurst) [inline src/components/ProcessingScreen.vue:9]:
```suggestion
		</EmptyContent>
		<progress :max="total" :value="progress" />
```

does that not work?

**Review by ChristophWurst — APPROVED** [review]
:sunglasses:

File: src/components/ProcessingScreen.vue (hunk 2 above)
Comment (st3iny) [reply src/components/ProcessingScreen.vue]: Done

**Review by st3iny — APPROVED** [review]
I killed some unused styles and added a little padding to the progress bar.

image
