### PR TITLE
fixed - Change New contact to Name

### LINKED ISSUE #3319: Change "New contact" wording to "Name"
### Describe the bug

When you click new contact, the default name for it its new contact. Should be name instead

### Steps to reproduce

Create a new contact
Look at the detailed view

### Expected behavior

The name is name and not new contact

### Actual behavior

The field is called new contact

### Contact version

_No response_

### Operating system

_No response_

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

Screenshot from 2023-04-18 14-48-07

### PR DESCRIPTION
**Pull request by tarunsamanta2k20**
Issue Desription:

Describe the bug
When you click new contact, the default name for it its new contact. Should be name instead

Steps to reproduce
Create a new contact
Look at the detailed view

Expected behavior
The name is name and not new contact

Actual behavior
The field is called new contact

Fixes #3319

### CODE REVIEW

File: src/views/Contacts.vue [hunk 1]
```diff
@@ -40,7 +40,7 @@
 				<template #icon>
 					<IconAdd :size="20" />
 				</template>
-				{{ t('contacts','New contact') }}
+				{{ t('contacts','Name') }}
```
Comment (ChristophWurst) [inline src/views/Contacts.vue:43]: this is the text for the left sidebar. I do not think this should change.

could you post before/after screenshots of the app, please? :)

**Review by ChristophWurst — CHANGES_REQUESTED** [review]

File: src/views/Contacts.vue (hunk 1 above)
Comment (tarunsamanta2k20) [reply src/views/Contacts.vue:43]: @ChristophWurst could you please know me how to run this app in localhost?

Comment (tarunsamanta2k20) [reply src/views/Contacts.vue:43]: @ChristophWurst In package.json there is no command for npm run start. Is there any other ways to run it on localhost?

Comment (ChristophWurst) [reply src/views/Contacts.vue:43]: See https://docs.nextcloud.com/server/latest/developer_manual/getting_started/devenv.html. You need a running Nextcloud instance for the Contacts app to work.

Comment (tarunsamanta2k20) [reply src/views/Contacts.vue:43]: @ChristophWurst my question is in package.json there is no command for running this app. You have sent me the tutorial for server repo.

Comment (ChristophWurst) [reply src/views/Contacts.vue:43]: It is not possible to run this app without Nextcloud server. Nextcloud server is the platform for apps.

Comment (ChristophWurst) [reply src/views/Contacts.vue:43]: https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#setup

**Review by st3iny — APPROVED** [review]
Tested and works. Please squash all commits into a single one and we're ready to merge.

Thanks for your contribution :)
