### PR TITLE
Fix address book picker

### LINKED ISSUE #2993: Can't move contact between address books
### Describe the bug

I should be able to change the address book of a contact via the select dropdown. This is not possible if I have multiple address books.

[empty-address-book-list.webm](https://user-images.githubusercontent.com/1479486/193046531-52b9a3ac-61b4-4678-86e1-aeee7b2247d0.webm)

### Steps to reproduce

1. Create an additional address book.
2. Edit a contact.
3. Scroll down and try to move it to another address book via the dropdown.

### Expected behavior

I should be able to move the contact to another address book.

### Actual behavior

It's not possible to move the contact.

### Contact version

main

### Additional info

cc @ChristophWurst

### PR DESCRIPTION
**Pull request by st3iny**
Fix #2993

The `options` prop is an empty array by default and `[] || b == []`. The component `PropertySelect` is not used anywhere else so this should be a safe change.

I also fixed a conflict error that occurred when picking the same address book as before. The contact should only be moved if the address book actually changes.

### CODE REVIEW

File: src/components/Properties/PropertySelect.vue [hunk 1]
```diff
@@ -39,7 +39,7 @@
 			</div>
 
 			<Multiselect v-model="matchedOptions"
-				:options="options || propModel.options"
+				:options="propModel.options || options"
```
Comment (ChristophWurst) [inline src/components/Properties/PropertySelect.vue:42]: Regression of org charts then. Good catch!

**Review by ChristophWurst — APPROVED** [review]
