### PR TITLE
ActionLink should be shown as a secondary button on quick actions

### LINKED ISSUE #3564: All quick actions should be secondary buttons
### Describe the bug

The mockup of https://github.com/nextcloud/contacts/issues/3365 says that all action icons should have the light blue outline. Only Talk has it:

Bildschirmfoto vom 2023-08-14 15-27-01

### Steps to reproduce

1. Create another user
2. Open that user's system address book contact

### Expected behavior

Icons with outlines

### Actual behavior

Some icons with outlines, some without

### Contact version

5.4

### Operating system

_No response_

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by GretaD**
Tested it on Nc/vue library and it works. 

fixes #3564

### CODE REVIEW

File: src/components/ContactDetails.vue [hunk 1]
```diff
@@ -222,25 +222,29 @@
...
 					</Actions>
-					<Actions v-if="phoneNumberProperties">
+					<Actions v-if="phoneNumberProperties"
+						type="secondary">
 						<template #icon>
 							<IconCall :size="20" />
 						</template>
 						<ActionLink v-for="phoneNumber in phoneNumberList"
 							:key="phoneNumber"
+							type="secondary"
```
Comment (st3iny) [inline src/components/ContactDetails.vue:247]:
```suggestion
```

See above.

**Review by st3iny — COMMENTED** [review]
Tested on server stable27 and works. Please take a look at my comments.
