### PR TITLE
Enhancement/allow year removal

### LINKED ISSUE #161: several problems with birthday without a year
Please note that I do not know, whether this is is a problem with the contacts app, the CardDaV core implementation, or a combination of both. 

### Steps to reproduce
1. In the contacts app, try to enter a Birthday without a year
2. Create a contact on your device without a year. Sync.
3. Create a contact on the MacOSX Contacts app. Sync.

### Expected behaviour
1. The date picker should allow you to check a box `omit year` or you should be able to enter the Birthday without a year manually.
2. The date should be synced without a year.
3. The date should be synced without a year.

### Actual behaviour
1. I cannot enter a birthday without a year manually. The birthday is never saved in the database. The datepicker forces you choose a year.
2. The birthday is missing from the VCARD on the server. Never shows up in the nextcloud contacts app.
```
BEGIN:VCARD
VERSION:4.0
PRODID:+//IDN bitfire.at//DAVdroid/1.4.0.3-ose vcard4android ez-vcard/0.10.
 1
UID:88e64a5b-c154-4d21-82f1-3800f9ff063b
FN:Birthday Without-Year
N:Without-Year;Birthday;;;
EMAIL;TYPE=home:no@birthday.com
REV:20170312T223956Z
END:VCARD
```
3. The year 1604 is shown in the nextcloud contacts app.
```
BEGIN:VCARD
VERSION:3.0
PRODID:-//Apple Inc.//Mac OS X 10.11.6//EN
N:Without-Year-OSX;Birthday;;;
FN:Birthday Without-Year-OSX
EMAIL;type=INTERNET;type=HOME;type=pref:no@birthday.com
BDAY;X-APPLE-OMIT-YEAR=1604:1604-06-20
REV:2017-03-12T22:42:30Z
UID:00eefa1d-32d2-4a61-bd6f-e127c2e69024
END:VCARD
```

**In all three cases the VCARD should contain the correct BDAY format for a birthday without a year. In the specifications for vcard 3.0 and 4.0, there are options to do so.**

### Server configuration
**Operating system**: Linux

**Web server:** Apache 2.4.25

**Database:** MySQL 5.6.25

**PHP version:** 5.6.30

**Nextcloud version:** 11.0.2

**Contacts version:** 1.5.3

**Updated from an older Nextcloud or fresh install:** updated: oc 8.2.9 -> nc 9.0.57 -> 10.0.4 -> 11.0.2

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.4.1
  - activitylog: 0.0.1
  - admin_audit: 1.1.0
  - announcementcenter: 3.0.0
  - apporder: 0.3.3
  - bookmarks: 0.9.1
  - calendar: 1.5.1
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - direct_menu: 0.10.0
  - external: 1.2
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_markdown: 1.0.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - systemtags: 1.1.3
  - tasks: 0.9.5
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_external: 0.4
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - survey_client
  - user_ldap
  - user_saml
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc2352d53521",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/data\/nextcloud\/data",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "installed": true,
        "forcessl": true,
        "loglevel": 2,
        "maintenance": false,
        "trusted_domains": [
            "cloud.evermeet.cx"
        ],
        "share_folder": "\/Shared",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logdateformat": "Y-m-d H:i:s O",
        "logtimezone": "Europe\/Vienna",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_from_address": "evercloud",
        "mail_domain": "evermeet.cx",
        "mail_smtpsecure": "tls",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/data\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "appstore.experimental.enabled": true,
        "trashbin_retention_obligation": "auto",
        "updater.release.channel": "stable",
        "htaccess.RewriteBase": "\/",
        "overwrite.cli.url": "https:\/\/cloud.evermeet.cx",
        "auth.bruteforce.protection.enabled": false
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 52, Chrome 57.0.2987.98

**Operating system:** Mac OSX 10.11.6

**CardDAV-clients:** DAVdroid 1.4.0.3-ose, OSX Contacts Sync (from the OS)

#### Web server error log
```
no errors (empty)
```

#### Nextcloud log (data/nextcloud.log)
```
no errors (empty)
```

#### Browser log
```
no errors (empty)
```

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/42954707-several-problems-with-birthday-without-a-year?utm_campaign=plugin&utm_content=tracker%2F46751899&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F46751899&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #625: Allow to set a date without a year
- [ ] For v4 only
The ui is already done, we now need to decide how to do that
- [ ] fixes #1041

Ref: https://github.com/nextcloud/contacts/issues/161
> The date picker should allow you to check a box omit year or you should be able to enter the Birthday without a year manually.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/63289845-allow-to-set-a-date-without-a-year?utm_campaign=plugin&utm_content=tracker%2F46751899&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F46751899&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #161
Fix #625

### CODE REVIEW

File: src/components/Actions/ActionCopyNtoFN.vue [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+import ActionsMixin from 'Mixins/ActionsMixin'
+
+export default {
+	name: 'ActionCopyNtoFN',
+	components: {
+		ActionButton
+	},
+	mixins: [ActionsMixin],
+	methods: {
+		copyNtoFN() {
```
Comment (ChristophWurst) [inline src/components/Actions/ActionCopyNtoFN.vue]:
```suggestion
		copyNToFN() {
```

https://stackoverflow.com/questions/15526107/acronyms-in-camelcase

File: src/components/Actions/ActionToggleYear.vue [hunk 2]
```diff
@@ -0,0 +1,94 @@
...
+		toggleYear() {
+			const dateObject = this.component.localValue.toJSON()
+
+			// year was already ignored: adding it back
+			if (this.omitYear) {
+				this.$nextTick(() => {
+					this.component.updateValue(dateObject, true)
+				})
+
+			// year was displayed: removing
```
Comment (ChristophWurst) [inline src/components/Actions/ActionToggleYear.vue]: nit: I would move such comments *into* the block, as first line

File: src/components/Actions/ActionToggleYear.vue [hunk 3]
```diff
@@ -0,0 +1,94 @@
...
+			} else {
+				// --0124 format
+				if (this.component.localContact.version === '4.0') {
```
Comment (ChristophWurst) [inline src/components/Actions/ActionToggleYear.vue]: `lse if(...)` for clearer coding style?
