### PR TITLE
fix: long contact name overlapping with other content

### LINKED ISSUE #3771: Long contact name overlapped by read-only icon
### Steps to reproduce

1. Enable the app contacts_interaction
2. Enable Mail
3. Send an email to a long email address
4. Open contacts

### Expected behavior

The read-only contact looks nice

### Actual behavior

Bildschirmfoto vom 2024-01-04 14-45-45

### Server operating system

_No response_

### Web server

None

### Database engine version

None

### PHP engine version

None

### Nextcloud version

_No response_

### Updated from an older installed version or fresh install

None

### Signing status

_No response_

### List of activated apps

_No response_

### Nextcloud configuration

_No response_

### Browser

_No response_

### Client operating system

_No response_

### CardDAV-clients

_No response_

### Web server error log

_No response_

### Nextcloud log

_No response_

### Browser log

_No response_

### Browser log

_No response_

### PR DESCRIPTION
**Pull request by PeterJGDe**
fixes #3771 

After:
image

### CODE REVIEW

File: src/components/ContactDetails.vue [hunk 1]
```diff
@@ -29,7 +29,7 @@
 
 				<!-- fullname -->
 				<template #title>
-					<div v-if="isReadOnly">
```
Comment (GretaD) [inline src/components/ContactDetails.vue:32]: in general, we call the classes something related to the section we are editing. In this case, it can be something like `'class=full-name' `or `'class=name-header'`

File: src/components/ContactDetails.vue [hunk 2]
```diff
@@ -29,7 +29,7 @@
...
+					<div v-if="isReadOnly" class="ellipsis">
```
Comment (GretaD) [inline src/components/ContactDetails.vue:32]: in general, we call the classes something related to the section we are editing. In this case, it can be something like `'class=full-name'` or `'class=name-header'`

**Review by GretaD — APPROVED** [review]
